#pragma once

enum SCENE_CREATE { SC_CURRENT, SC_NEXT };

enum MOVE_DIR { MD_BACK = -1, MD_NONE, MD_FRONT };

enum COLLIDER_TYPE { CT_RECT, CT_CIRCLE, CT_LINE, CT_POINT, CT_PIXEL };
enum COLLISION_STATE { CS_ENTER, CS_STAY, CS_LEAVE, CS_END };

enum ANIMATION_TYPE {
	AT_ATLAS, AT_FRAME, AT_END
};
enum ANIMATION_OPTION {
	AO_LOOP, AO_ONCE_RETURN, AO_ONCE_DESTROY, AO_TIME_RETURN, AO_TIME_DESTROY, AO_END
};
